# Platform, Min OS Version
platform :ios, '7.0'

# Default Pods
# pod 'CocoaLumberjack'
# pod 'AFNetworking'

# RZUtils Examples. Uncomment as necessary.
# https://github.com/Raizlabs/RZUtils for more info
#
  pod 'RZUtils'                         # All of RZUtils
# pod 'RZUtils/Categories'              # All Categories
# pod 'RZUtils/Components'              # All Components
# pod 'RZUtils/Categories/NSString'     # Specific Categories
# pod 'RZUtils/Components/RZButtonView  # Specific Components
